dist: trusty
language: node_js
node_js:
  - "16.10.0"
sudo: false
branches:
  only:
    - master
notifications:
  email:
    on_success: change
    on_failure: always
cache: yarn
script:
  - add-apt-repository ppa:avsm/ppa
  - apt update
  - apt install opam
  - opam init --auto-setup
  - npm install -g esy
  - cd ./tools/comment-ppx && bash ./scripts/install.sh
  - cd ../..
  - yarn build
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
